# Use root/example as user/password credentials
version: '3.6'

services:
  fastapi:
    build: .
    image: fastapi
    depends_on:
      - mysql
    container_name: fastapi
    restart: always
    environment:
      ENTORNO: ${ENTORNO}
      MYSQL_USER: ${MAIN_USER}
      MYSQL_PASSWORD: ${PASSWORD_USER}
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    networks:
      - app-network
  mysql:
    image: mysql
    container_name: mysql
    platform: linux/x86_64 #Fix for Apple M1
    command: --default-authentication-plugin=mysql_native_password #Para la version 8 puede que la 5.7 no la necesites
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT}
      MYSQL_USER: ${MAIN_USER}
      MYSQL_PASSWORD: ${PASSWORD_USER}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log
      - ./mysql/script/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql/script/data.sql:/docker-entrypoint-initdb.d/2.sql
    networks:
      - app-network
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    environment: 
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DESIGN: rmsoft
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
#volumes:
#  dbdata:
#    driver: local